import type { Metadata } from "next";
import { Onest, Figtree } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider";

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=clash-display@400,500,600,700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${onest.variable} ${figtree.variable} antialiased px-6 py-4 sm:px-8 sm:py-6 md:px-12 md:py-8 lg:px-96 lg:py-10 bg-white dark:bg-black`}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
